module.exports = {
  client_id: "YOUR CLIENT ID HERE",
  client_secret: "YOUR CLIENT SECRET HERE",
  access_token: "YOUR ACCESS TOKEN HERE",
};

// EncryptedData = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJldmVudF90eXBlIjoicGF5bWVudC5jb21wbGV0ZWQiLCJjcmVhdGVkIjoiMjAyMy0wMi0xMlQxOTo1MTo1MS4yMTZaIiwicGF5bWVudCI6eyJpZCI6IjYzYmZlNmFhNmZhN2JmMDUxOTU0ZTdkZiIsImFtb3VudCI6MTAwLCJjbGllbnQiOiJvbGl2ZXJtYzMiLCJtZW1vIjoidGVzdCIsInNhbmRib3giOmZhbHNlLCJtZXRhZGF0YSI6eyJpZCI6IjEyMyJ9LCJzdWNjZXNzIjp0cnVlfSwiaWF0IjoxNjc2MjMxNTExfQ.q-iRL0-O3Ud_oxVZLehQZTq6THwTtnDhsi99aqBEtl8"
